### creating database / schema
CREATE DATABASE customer_behavior;

use customer_behavior;

select * from customer;


# Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender ;


#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer) ;

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

# Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


 # Do subscribed customers spend more? Compare average spend and total revenue 
 # between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spent,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spent DESC;

# Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

# Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


# Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


# Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


# Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

# Q11. Which locations generate the highest total revenue and average purchase value?
SELECT Location,
       SUM(Purchase_Amount) AS Total_Revenue,
       ROUND(AVG(Purchase_Amount), 2) AS Avg_Spend
FROM customer
GROUP BY Location
ORDER BY Total_Revenue DESC;


# Q12. How does purchase amount vary by season across different product categories?
SELECT Season,
       Category,
       SUM(Purchase_Amount) AS Revenue
FROM customer
GROUP BY Season, Category
ORDER BY Season, Revenue DESC;


# Q13. Which payment methods are associated with higher average purchase amounts?
SELECT Payment_Method,
       ROUND(AVG(Purchase_Amount), 2) AS Avg_Purchase
FROM customer
GROUP BY Payment_Method;


# Q14. Do customers who receive discounts make more repeat purchases than those who don’t?
SELECT Discount_Applied,
       ROUND(AVG(Previous_Purchases), 2) AS Avg_Previous_Purchases,
       COUNT(*) AS Customer_Count
FROM customer
GROUP BY Discount_Applied;


# Q15. What is the relationship between review rating and repeat purchases?
SELECT Review_Rating,
       ROUND(AVG(Previous_Purchases), 2) AS Avg_Repeat_Purchases
FROM customer
GROUP BY Review_Rating
ORDER BY Review_Rating DESC;


# Q16. Which shipping type results in the highest customer spending and repeat purchases?
SELECT Shipping_Type,
       ROUND(AVG(Purchase_Amount), 2) AS Avg_Spend,
       ROUND(AVG(Previous_Purchases), 2) AS Avg_Repeat_Purchases
FROM customer
GROUP BY Shipping_Type;


# Q17. Which product categories have the highest proportion of loyal customers?
SELECT Category,
       COUNT(*) AS Loyal_Customer_Count
FROM customer
WHERE Previous_Purchases > 5
GROUP BY Category
ORDER BY Loyal_Customer_Count DESC;


# Q18. How does frequency of purchases (Weekly, Monthly, Annually) impact total revenue contribution?
SELECT Frequency_of_Purchases,
       SUM(Purchase_Amount) AS Total_Revenue
FROM customer
GROUP BY Frequency_of_Purchases
ORDER BY Total_Revenue DESC;


# Q19. Are younger or older customers more responsive to discounts ?
SELECT Age_Group,
       ROUND(
           100.0 * SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*), 2
       ) AS Discount_Usage_Percentage
FROM customer
GROUP BY Age_Group;


# Q20. Which combinations of category + season + discount generate the highest revenue?
SELECT Category,
       Season,
       Discount_Applied,
       SUM(Purchase_Amount) AS Total_Revenue
FROM customer
GROUP BY Category, Season, Discount_Applied
ORDER BY Total_Revenue DESC;
